version: '3.8'
networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: "172.18.0.0/16"
                    gateway: 172.18.0.1


services:
    # php
    gigaprog-php:
        container_name: gigaprog-php
        build:
            context: .
            target: php
            dockerfile: Dockerfile
        working_dir: /var/www/gigaprog
        volumes:
            - .:/var/www/gigaprog
        ports:
            - '8080:80'
        depends_on:
            - gigaprog-db
        networks:
            app_net:
                ipv4_address: 172.18.0.5

    # database
    gigaprog-db:
        container_name: gigaprog-db
        image: postgres
        restart: always
        expose:
            - 5432
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - storage-data:/var/lib/postgresql
        networks:
            app_net:
                ipv4_address: 172.18.0.3

    gigaprog-pgadmin:
        container_name: gigaprog-pgadmin
        image: dpage/pgadmin4
        ports:
            - "5080:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        depends_on:
            - gigaprog-db
        networks:
            app_net:
                ipv4_address: 172.18.0.4

volumes:
    storage-data: ~


